name: "Build"

on:
  push:
    branches-ignore:
      - main

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Say Hello
        run: echo "Hello!"
